"""Switch integer primary keys to UUIDs

Revision ID: 0001_uuid_pks
Revises:
Create Date: 2026-07-27

Fresh installs get UUID columns straight from ``Base.metadata.create_all`` in
``app.main``, so this migration exists for databases created before the switch.
It rewrites every ``id`` column in place and remaps ``leads.course_id`` through
the new keys, so existing rows and their relationships survive.
"""

from alembic import op

revision = "0001_uuid_pks"
down_revision = None
branch_labels = None
depends_on = None

TABLES = ("users", "courses", "teachers", "leads")


def upgrade() -> None:
    # 1. Stage a UUID next to every integer id. gen_random_uuid() is built into
    #    PostgreSQL 13+, so no extension is required.
    for table in TABLES:
        op.execute(
            f"ALTER TABLE {table} ADD COLUMN uuid_id uuid NOT NULL DEFAULT gen_random_uuid()"
        )

    # 2. Translate the foreign key while both id sets are still present.
    op.execute("ALTER TABLE leads ADD COLUMN uuid_course_id uuid")
    op.execute(
        "UPDATE leads l SET uuid_course_id = c.uuid_id FROM courses c WHERE l.course_id = c.id"
    )
    op.execute("ALTER TABLE leads DROP CONSTRAINT leads_course_id_fkey")
    op.execute("ALTER TABLE leads DROP COLUMN course_id")
    op.execute("ALTER TABLE leads RENAME COLUMN uuid_course_id TO course_id")

    # 3. Promote the UUID column to primary key. Dropping the old column also
    #    drops its owned sequence and its indexes.
    for table in TABLES:
        op.execute(f"ALTER TABLE {table} DROP CONSTRAINT {table}_pkey")
        op.execute(f"ALTER TABLE {table} DROP COLUMN id")
        op.execute(f"ALTER TABLE {table} RENAME COLUMN uuid_id TO id")
        # Ids are generated by the model's `default=uuid.uuid4`, matching what
        # create_all produces on a fresh database.
        op.execute(f"ALTER TABLE {table} ALTER COLUMN id DROP DEFAULT")
        op.execute(f"ALTER TABLE {table} ADD CONSTRAINT {table}_pkey PRIMARY KEY (id)")

    # 4. Restore the relationship and the indexes the models declare.
    op.execute(
        "ALTER TABLE leads ADD CONSTRAINT leads_course_id_fkey "
        "FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE SET NULL"
    )
    for table in TABLES:
        op.execute(f"CREATE INDEX ix_{table}_id ON {table} (id)")
    op.execute("CREATE INDEX ix_leads_course_id ON leads (course_id)")


def downgrade() -> None:
    """Restore integer primary keys.

    Relationships are preserved, but the original integer values are not:
    rows are renumbered from 1 in insertion order.
    """
    # 1. Stage a fresh integer id. Adding a serial column numbers existing rows.
    for table in TABLES:
        op.execute(f"ALTER TABLE {table} ADD COLUMN int_id serial")

    # 2. Translate the foreign key while both id sets are still present.
    op.execute("ALTER TABLE leads ADD COLUMN int_course_id integer")
    op.execute(
        "UPDATE leads l SET int_course_id = c.int_id FROM courses c WHERE l.course_id = c.id"
    )
    op.execute("ALTER TABLE leads DROP CONSTRAINT leads_course_id_fkey")
    op.execute("ALTER TABLE leads DROP COLUMN course_id")
    op.execute("ALTER TABLE leads RENAME COLUMN int_course_id TO course_id")

    # 3. Promote the integer column back to primary key.
    for table in TABLES:
        op.execute(f"ALTER TABLE {table} DROP CONSTRAINT {table}_pkey")
        op.execute(f"ALTER TABLE {table} DROP COLUMN id")
        op.execute(f"ALTER TABLE {table} RENAME COLUMN int_id TO id")
        op.execute(f"ALTER TABLE {table} ADD CONSTRAINT {table}_pkey PRIMARY KEY (id)")

    # 4. Restore the relationship and the indexes the models declare.
    op.execute(
        "ALTER TABLE leads ADD CONSTRAINT leads_course_id_fkey "
        "FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE SET NULL"
    )
    for table in TABLES:
        op.execute(f"CREATE INDEX ix_{table}_id ON {table} (id)")
    op.execute("CREATE INDEX ix_leads_course_id ON leads (course_id)")
